remote_theme: pages-themes/slate@v0.2.0
plugins:
        - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Ian Outhwaite
description: Honey, high jumping, and hiking. Loves cheesing but is lactose intolerant.
logo: /assets/iouthwaite_headshot.png
